# https://github.com/jj-vcs/jj/blob/main/docs/config.md

"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "xorphitus"
email = "xorphitus@gmail.com"

[ui]
editor = "emacsclient -c -a nano"
diff-editor = "meld"

[aliases]
aicommit = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
OLLAMA_MODEL=gpt-oss:20b
CLAUDE_MODEL=haiku

DIFF=$(jj diff --git)
PROMPT="Generate ONLY a one-line jj commit message in English. The message should follow Conventional Commits format 'type(scope): description'. Types: feat, fix, docs, style, refactor, test, chore. Based strictly on the diff. Output ONLY the message, nothing else. Here are the diff\n: ${DIFF}"

MSG=""
if [ -x "$(command -v ollama)" ]; then
MSG=$(ollama run --hidethinking "$OLLAMA_MODEL" "$PROMPT")
else
MSG=$(claude --no-session-persistence --model "$CLAUDE_MODEL" --print "$PROMPT")
fi

jj commit -m "$MSG"
""", ""]

bpush = ["util", "exec", "--", "bash", "-c", """
set -euo pipefail
branch="$1"
jj bookmark set "$branch" -r @-
jj git push -b "$branch" --allow-new
""", ""]

[merge-tools.meld]
program = "meld"
edit-args = ["--newtab", "$left", "$right"]
