{ pkgs, lib, ... }:

# Generated by Claude Code

pkgs.stdenv.mkDerivation rec {
  pname = "devtoys-cli";
  version = "2.0.8.0";

  src = pkgs.fetchzip {
    url = "https://github.com/DevToys-app/DevToys/releases/download/v${version}/devtoys.cli_linux_x64_portable.zip";
    sha256 = "03z7b5gx65d6rkc9cj8fgmwsmqq8l56yzwnd6mrll306h46k8qmg";
    stripRoot = false;
  };

  nativeBuildInputs = with pkgs; [
    makeWrapper
  ];

  buildInputs = with pkgs; [
    dotnet-runtime_8
    icu
  ];

  dontPatchELF = true;
  dontStrip = true;

  installPhase = ''
    runHook preInstall

    mkdir -p $out/bin $out/lib/devtoys-cli
    cp -r * $out/lib/devtoys-cli/

    chmod +x $out/lib/devtoys-cli/DevToys.CLI

    makeWrapper $out/lib/devtoys-cli/DevToys.CLI $out/bin/devtoys \
      --prefix PATH : "${lib.makeBinPath [pkgs.dotnet-runtime_8]}" \
      --set DOTNET_ROOT "${pkgs.dotnet-runtime_8}" \
      --prefix LD_LIBRARY_PATH : "${lib.makeLibraryPath buildInputs}"

    runHook postInstall
  '';

  meta = with lib; {
    description = "A Swiss Army knife for developers - CLI version";
    homepage = "https://github.com/DevToys-app/DevToys";
    license = licenses.mit;
    platforms = platforms.linux;
    maintainers = [ ];
  };
}
